M48
; DRILL file {KiCad 9.0.3} date 2025-12-24T22:58:58+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-24T22:58:58+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.450
%
G90
G05
T1
X262.4Y-86.0
T2
X184.96Y-100.6
X257.18Y-138.5
T3
X186.05Y-61.05
X263.9Y-138.9
T4
X193.43Y-138.5
X193.47Y-116.6
X248.67Y-122.5
X248.71Y-100.6
M30
