---
  - topic_name: "joint_state1"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state2"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state3"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state4"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state5"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state6"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state7"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state8"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state9"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state10"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state11"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
  - topic_name: "joint_state12"
    ros_type_name: "std_msgs/msg/Float64"
    gz_type_name: "gz.msgs.Float"
    direction: ROS_TO_GZ
